version: 2.0
jobs:
  test:
    docker:
            - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: gradle-test
          command:
            gradle test
      - store_test_results:
              path: build/test-results


jobs:
  package:
    docker:
            - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          command:
            gradle jar
      - store_artifacts:
              path: build/libs
              destination: prefix
workflows:
        version: 2.0
        two_job_flow:
                jobs:
                        - test
                        - package:
                                required:
                                        - test
                                  



